services:
  database:
    image: mongo:6
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  y-websocket:
    image: registry.uni-kassel.dev/y-websocket-server:latest
    build:
      platforms: [ linux/amd64, linux/arm64 ]
      context:  ./apps/y-websocket-server
    ports:
      - "1234:1234"
    restart: unless-stopped
volumes:
  data:
