apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.common.name }}
spec:
  selector:
    app: {{ .Values.common.name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
