replicaCount: 1

image:
  repository: registry.uni-kassel.dev/y-websocket-server
  tag: latest
  pullPolicy: Always
  pullSecrets:
    - name: vs-registry

common:
  name: y-websocket-server
  issuer: letsencrypt-prod

service:
  type: ClusterIP
  port: 1234

ingress:
  enabled: true
  hosts:
    - host: yjs.uni-kassel.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - yjs.uni-kassel.dev
      secretName: y-websocket-tls
